sudo: true

language: python
python:
  - "3.5"
<<<<<<< HEAD
  - "2.7"
=======
>>>>>>> e96424217cbc37538dc19b2407b9fe31ffe88215
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: 
  nosetests --with-coverage --cover-package=app
after_success:
<<<<<<< HEAD
  - coveralls
=======
  - coveralls
>>>>>>> e96424217cbc37538dc19b2407b9fe31ffe88215
